### ISSUE TITLE
EDITINPLACE

### ISSUE THREAD

**Issue by unhandyandy** [nosuchtim/keykit#3453]
I see this in cmds.k:

`#define EDITINPLACE(p,expr) origt=p%(1).time;p.time-=origt;p.length=latest(p);p=expr;p.time+=origt`

Is that a macro?  I don't think you mentioned macros in the docs.

If so, why do you change certain values of `p`, and then just replace p by `expr`?

**Comment by nosuchtim** [comment]
#define is described in the keykit language spec, doc/language.{html,pdf}

That macro applies a transformation (the expr) to a phrase, while
preserving any blank space at the beginning of the phrase.   It's a
convenience macro just for lib/cmds.k, not useful elsewhere.

      ...Tim...

**Comment by unhandyandy** [comment]
Thanks.  I missed it in language.html.

But I'm still puzzled by `p=expr`.  Does that mean something like
`p = expr(p,...)`
?
Otherwise, I don't see what good it does to change parameters of p _before_ applying `p=expr`.

**Comment by unhandyandy** [comment]
OK thanks, I missed it in language.html.

And I forgot that since it's a macro, `expr` isn't evaluated till runtime.  I'm not a real programmer, but I think I get it now.

**Comment by unhandyandy** [comment]
Btw, let me repeat once again my appreciation and admiration for Keykit - I use it every day.
