### ISSUE TITLE
Nicolas Grenier in contrib folder

### ISSUE THREAD

**Issue by ncg777** [nosuchtim/keykit#3455]
Hi Mr Thompson and others! Remember me? Old code "of mine" is still in Keykit's contrib folder.

I don't remember how it got there but my full name is Nicolas Couture-Grenier, not Nicolas Grenier and my code has evolved into blahlib, which I pushed for the first time on github today (https://github.com/ncg777/blahlib).

I don't know what's best to do about this. Maybe nothing is even an option! In a way, I hope not too many people depend on it. It's a bit better now and mostly retro compatible. You may also have a look at the "burst.k" file and the bst folder, which I still use to compose, although it is admittedly quite a messy file. There are also .bst compositions in my repo along with the midi files, some of which I can no longer render because of breaking changes over the years. 

I use Forte numbers for pitch class sets now, but my older notation, based on counting binary necklaces is still in scale.k. Believe it or not, the notations don't overlap because my other notation is zero-padded (07-43.11 vs 7-35.11 for example; was that close!). I also offer .sed files in the bst folder to convert between the 2 notations.

I still am a Keykit fan and user. How is that even possible after all these years! And it still works like a charm! 😁

Cheers!

**Comment by nosuchtim** [comment]
Hi Nicolas!

I'm thinking I should just include a pointer to your Github repo, and
remove the files in the contrib directory.  Your existing contrib directory
has an HTML file documenting the functions.  I haven't figured out how to
display the docs/docu.xml file in your repo - how do you do that?

      ...Tim...

**Comment by ncg777** [comment]
Sure, some sort of github pointer to my repo would be perfect if it's possible. As long as it is not frozen in time with me unable to fix it.

The documentation I wrote back then is wildly out of date (more than a decade?) even though it still is correct as far as I know. XSL (xml style sheets) is a way to turn XML into anything else, including HTML, which is what this style sheet does. It used to be rendered by browsers but this is no longer the case for whatever reason I don't know; probably security. I have yet to find a solution to run it again but I am sure there are simple ways.

blahlib is kind of integrated through the BST format (burst.k) and I have not documented it much. At heart it is quite simple and compact. I tried to write a BNF grammar (there are probably a few problems with it). There are plenty of examples in the bst folder though.

**Comment by ncg777** [comment]
https://github.com/ncg777/blahlib/blob/main/readme.md

**Comment by ncg777** [comment]
FYI, I moved my personal BST and MIDI files in another public repo, to separate concerns...

I guess it's possible to put a repo within a repo, as long as the inner repo is in an ignored directory.

**Comment by nosuchtim** [comment]
Fixed by commit 2e30807
