### ISSUE TITLE
Where are the older versions?

### ISSUE THREAD

**Issue by ncg777** [nosuchtim/keykit#3457]
Please post older versions as releases or something. In the worst case, virtual machines with old OSes may run them I guess.

**Comment by ncg777** [comment]
[key76e_src.zip](https://github.com/user-attachments/files/17968738/key76e_src.zip)
[key77b_src.zip](https://github.com/user-attachments/files/17968739/key77b_src.zip)

**Comment by nosuchtim** [comment]
fixed by commit 2e30807

**Comment by ncg777** [comment]
Sorry for being annoying!
