### ISSUE TITLE
Fatal error: couldn't find keyrc!?  You should run 'resetkeylib'

### ISSUE THREAD

**Issue by JRSV** [nosuchtim/keykit#8]
when I try to run bin/key I get a flash of a window that closes immediately and then the error

what does this mean? How do I get keyrc?  how do I run resetkeylib? it provides no information on this.
please help

MXLinux (debian 10)

**Comment by nosuchtim** [comment]
You can either:
1) cd to the bin directory and execute ./key
or
2) Add the bin directory to your PATH and execute key
I'm making changes to README.linux to explain this.

**Comment by nosuchtim** [comment]
Fixed with commit da16a4f242d915c396f11c9b3d25a3de7d79e79f

**Comment by nosuchtim** [comment]
If 1. or 2. in the comment above doesn't work for you, grab the updated dist/key_linux.zip which should handle things better now.

If you still have a "window flash" and nothing else, you can execute "key -e" which will generate a key.dbg file with debugging info.

**Comment by nosuchtim** [comment]
Re-open or submit a new issue if you're still having a problem.
